# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
source 'git@github.com:sicpa-dlab/didcomm-rust.git'

target 'DidcommExampleiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DidcommSDK', '0.3.1'

end
